//! Golden vectors for the zkVM integration, work-plan step 1 of docs/ZKVM_INTEGRATION.md.
//!
//! The single source of every constant is the committed fixture
//! `test/vectors/zkvm_golden.json` in the main repository, generated by circomlibjs (the
//! reference the circuits are built against) and regenerated-and-compared by
//! `test/zkvm_vectors.test.js`. This crate parses THAT file (embedded at compile time), so
//! the Rust side holds no copy of its own and cannot drift together with it. If these
//! tests pass, light-poseidon reproduces circomlibjs for both formula forms the guest
//! needs, the design's hard prerequisite, and the SHA-256 tree spec matches on both sides.
//! If they fail, the fallback is porting the circomlib constants, not changing the formula.

use ark_bn254::Fr;
use ark_ff::{BigInteger, PrimeField};
use light_poseidon::{Poseidon, PoseidonHasher};
use serde::Deserialize;
use sha2::{Digest, Sha256};
use std::sync::OnceLock;

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Fixture {
    #[serde(rename = "poseidon1_of_1")]
    pub poseidon1_of_1: String,
    #[serde(rename = "poseidon1_of_pMinus1")]
    pub poseidon1_of_p_minus_1: String,
    #[serde(rename = "kh_d1")]
    pub kh_d1: String,
    #[serde(rename = "kh_d2")]
    pub kh_d2: String,
    #[serde(rename = "rn_d1")]
    pub rn_d1: String,
    #[serde(rename = "rn_d2")]
    pub rn_d2: String,
    pub season: String,
    pub context_hash: String,
    pub gen_keyid_hex: String,
    pub empty_leaf_hash_hex: String,
    pub empty_depth16_hex: String,
    pub root_two_leaves_hex: String,
    pub root_two_leaves_right_hex: String,
    pub journal_left_hex: String,
    pub varied: Varied,
}

/// A fully-varied second witness so the guest check validates a whole journal that differs in
/// every field, not just the all-ones base case.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Varied {
    pub d_hex: String,
    pub secret: String,
    pub season: String,
    pub context_hash: String,
    pub keyid_hex: String,
    pub sibling0_hex: String,
    pub commitment: String,
    pub reg_nullifier: String,
    pub root_hex: String,
    pub journal_hex: String,
}

/// The parsed golden fixture, embedded from the main repository at compile time.
pub fn golden() -> &'static Fixture {
    static FIXTURE: OnceLock<Fixture> = OnceLock::new();
    FIXTURE.get_or_init(|| {
        serde_json::from_str(include_str!("../../../../test/vectors/zkvm_golden.json"))
            .expect("test/vectors/zkvm_golden.json must parse")
    })
}

/// The 4 little-endian 64-bit limbs of d = n - 2, matching prover/two_tier.js privToLimbs.
pub const D2_LIMBS: [u64; 4] = [
    0xbfd2_5e8c_d036_413f,
    0xbaae_dce6_af48_a03b,
    0xffff_ffff_ffff_fffe,
    0xffff_ffff_ffff_ffff,
];

pub fn fr_dec(x: Fr) -> String {
    x.into_bigint().to_string()
}

/// A pinned decimal field-element constant as 32 big-endian bytes, the journal encoding.
pub fn dec_to_be32(s: &str) -> [u8; 32] {
    use core::str::FromStr;
    let v = Fr::from_str(s).expect("constant must be a canonical decimal field element");
    fr_to_be32(v)
}

/// A field element as 32 big-endian bytes, left-padded, the journal encoding.
pub fn fr_to_be32(v: Fr) -> [u8; 32] {
    let bytes = v.into_bigint().to_bytes_be();
    let mut out = [0u8; 32];
    out[32 - bytes.len()..].copy_from_slice(&bytes);
    out
}

pub fn sha256(data: &[u8]) -> [u8; 32] {
    let mut out = [0u8; 32];
    out.copy_from_slice(&Sha256::digest(data));
    out
}

/// Leaf hash of the pinned spec: SHA-256(0x00 || keyID20).
pub fn leaf_hash(key_id: &[u8; 20]) -> [u8; 32] {
    let mut buf = Vec::with_capacity(21);
    buf.push(0x00);
    buf.extend_from_slice(key_id);
    sha256(&buf)
}

/// Internal node of the pinned spec: SHA-256(0x01 || left || right).
pub fn node_hash(left: &[u8; 32], right: &[u8; 32]) -> [u8; 32] {
    let mut buf = Vec::with_capacity(65);
    buf.push(0x01);
    buf.extend_from_slice(left);
    buf.extend_from_slice(right);
    sha256(&buf)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn poseidon_single_input_matches_the_fixture() {
        let g = golden();
        let mut h = Poseidon::<Fr>::new_circom(1).expect("poseidon width 1");
        assert_eq!(fr_dec(h.hash(&[Fr::from(1u64)]).unwrap()), g.poseidon1_of_1);
        let p_minus_1 = Fr::from(0u64) - Fr::from(1u64);
        assert_eq!(fr_dec(h.hash(&[p_minus_1]).unwrap()), g.poseidon1_of_p_minus_1);
    }

    #[test]
    fn poseidon_limb_and_nullifier_forms_match_the_fixture() {
        let g = golden();
        let mut h4 = Poseidon::<Fr>::new_circom(4).expect("poseidon width 4");
        let mut h3 = Poseidon::<Fr>::new_circom(3).expect("poseidon width 3");

        let kh1 = h4
            .hash(&[Fr::from(1u64), Fr::from(0u64), Fr::from(0u64), Fr::from(0u64)])
            .unwrap();
        assert_eq!(fr_dec(kh1), g.kh_d1);

        let d2: Vec<Fr> = D2_LIMBS.iter().map(|&l| Fr::from(l)).collect();
        let kh2 = h4.hash(&d2).unwrap();
        assert_eq!(fr_dec(kh2), g.kh_d2);

        use core::str::FromStr;
        let season = Fr::from_str(&g.season).unwrap();
        let ctx = Fr::from_str(&g.context_hash).unwrap();
        assert_eq!(fr_dec(h3.hash(&[kh1, season, ctx]).unwrap()), g.rn_d1);
        assert_eq!(fr_dec(h3.hash(&[kh2, season, ctx]).unwrap()), g.rn_d2);
    }

    #[test]
    fn decimal_to_journal_bytes_round_trips() {
        use core::str::FromStr;
        let g = golden();
        for c in [
            &g.poseidon1_of_1,
            &g.poseidon1_of_p_minus_1,
            &g.kh_d1,
            &g.kh_d2,
            &g.rn_d1,
            &g.rn_d2,
        ] {
            let bytes = dec_to_be32(c);
            let back = Fr::from_str(c).unwrap();
            assert_eq!(fr_to_be32(back), bytes);
            assert_eq!(&fr_dec(back), c);
        }
    }

    #[test]
    fn sha256_tree_spec_matches_the_fixture_both_directions() {
        let g = golden();
        let empty_leaf = leaf_hash(&[0u8; 20]);
        assert_eq!(hex::encode(empty_leaf), g.empty_leaf_hash_hex);

        let mut empty = vec![empty_leaf];
        for i in 1..=16 {
            let prev = empty[i - 1];
            empty.push(node_hash(&prev, &prev));
        }
        assert_eq!(hex::encode(empty[16]), g.empty_depth16_hex);

        let gen_keyid: [u8; 20] = hex::decode(&g.gen_keyid_hex).unwrap().try_into().unwrap();
        let keyid2 = [0x02u8; 20];
        let mut left = node_hash(&leaf_hash(&gen_keyid), &leaf_hash(&keyid2));
        let mut right = node_hash(&leaf_hash(&keyid2), &leaf_hash(&gen_keyid));
        for level in empty.iter().take(16).skip(1) {
            left = node_hash(&left, level);
            right = node_hash(&right, level);
        }
        assert_eq!(hex::encode(left), g.root_two_leaves_hex);
        assert_eq!(hex::encode(right), g.root_two_leaves_right_hex);
    }

    #[test]
    fn the_journal_layout_reproduces_the_javascript_built_fixture_journal() {
        // The fixture's journal hex was built in JavaScript with independent encoding, so
        // this catches a shared Rust-side layout or endianness mistake.
        let g = golden();
        let mut journal = Vec::with_capacity(136);
        journal.extend_from_slice(&dec_to_be32(&g.poseidon1_of_1));
        journal.extend_from_slice(&dec_to_be32(&g.rn_d1));
        journal.extend_from_slice(&hex::decode(&g.root_two_leaves_hex).unwrap());
        let season: u64 = g.season.parse().unwrap();
        journal.extend_from_slice(&season.to_be_bytes());
        journal.extend_from_slice(&dec_to_be32(&g.context_hash));
        assert_eq!(journal.len(), 136);
        assert_eq!(hex::encode(journal), g.journal_left_hex);
    }

    #[test]
    fn the_varied_witness_journal_reproduces_the_javascript_literal() {
        // Every field of the varied witness differs from the base case (season above 2^32, a
        // nontrivial secret and context, the right-hand root), so reproducing its JS-authored
        // journal literal from Rust pins the layout across the whole value range, not just the
        // all-ones case.
        let v = &golden().varied;
        let mut journal = Vec::with_capacity(136);
        journal.extend_from_slice(&dec_to_be32(&v.commitment));
        journal.extend_from_slice(&dec_to_be32(&v.reg_nullifier));
        journal.extend_from_slice(&hex::decode(&v.root_hex).unwrap());
        let season: u64 = v.season.parse().unwrap();
        journal.extend_from_slice(&season.to_be_bytes());
        journal.extend_from_slice(&dec_to_be32(&v.context_hash));
        assert_eq!(hex::encode(journal), v.journal_hex);
    }
}
